### ISSUE TITLE
It may crash when using Multi-threading

### ISSUE THREAD

**Issue by HoneyLuka** [jsonmodel/jsonmodel#528] opened 2016-08-29 07:07 UTC
HI.
I'm using v1.4.0 in code.

Here is log in main thread:
```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x182a15b88 objc_msgSend + 8
1  CoreFoundation                 0x183284260 -[__NSDictionaryM setObject:forKey:] + 360
2  MONO                           0x10077d324 -[NSMutableDictionary(JPFMyDictionary) setObject:forKeyedSubscript:] + 4302705444
3  MONO                           0x10039e2f4 -[JSONModel __customSetValue:forProperty:] (JSONModel.m:850)
4  MONO                           0x10039bbac -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:341)
5  MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
6  MONO                           0x10039bcf4 -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:372)
7  MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
8  MONO                           0x10039f2b4 +[JSONModel arrayOfModelsFromDictionaries:error:] (JSONModel.m:1119)
9  MONO                           0x10039d458 -[JSONModel __transform:forProperty:error:] (JSONModel.m:750)
10 MONO                           0x10039bdcc -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:399)
11 MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
12 MONO                           0x1001178e4 -[RecommendContentItemViewController requestSuccess:isPullRefresh:] (RecommendContentItemViewController.m:793)
13 MONO                           0x100116f44 __97-[RecommendContentItemViewController requestRecommendDataWithFirstFetch:fromStart:isPullRefresh:]_block_invoke (RecommendContentItemViewController.m:717)
14 libdispatch.dylib              0x182de94bc _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x182de947c _dispatch_client_callout + 16
16 libdispatch.dylib              0x182deeb84 _dispatch_main_queue_callback_4CF + 1844
17 CoreFoundation                 0x183354d50 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
18 CoreFoundation                 0x183352bb8 __CFRunLoopRun + 1628
19 CoreFoundation                 0x18327cc50 CFRunLoopRunSpecific + 384
20 GraphicsServices               0x184b64088 GSEventRunModal + 180
21 UIKit                          0x188566088 UIApplicationMain + 204
22 MONO                           0x10016bacc main (main.m:35)
23 libdispatch.dylib              0x182e1a8b8 (Missing)
```

at the same time in background thread:
```
com.mmmono.mono_tea_manager_queue
0  libsystem_malloc.dylib         0x182f61508 szone_malloc_should_clear + 104
1  libsystem_malloc.dylib         0x182f65930 malloc_zone_calloc + 124
2  libsystem_malloc.dylib         0x182f65930 malloc_zone_calloc + 124
3  libsystem_malloc.dylib         0x182f65890 calloc + 60
4  CoreFoundation                 0x1832841a8 -[__NSDictionaryM setObject:forKey:] + 176
5  MONO                           0x10077d324 -[NSMutableDictionary(JPFMyDictionary) setObject:forKeyedSubscript:] + 4302705444
6  MONO                           0x10039e2f4 -[JSONModel __customSetValue:forProperty:] (JSONModel.m:850)
7  MONO                           0x10039bbac -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:341)
8  MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
9  MONO                           0x10039bcf4 -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:372)
10 MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
11 MONO                           0x10039bcf4 -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:372)
12 MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
13 MONO                           0x10039f2b4 +[JSONModel arrayOfModelsFromDictionaries:error:] (JSONModel.m:1119)
14 MONO                           0x10039d458 -[JSONModel __transform:forProperty:error:] (JSONModel.m:750)
15 MONO                           0x10039bdcc -[JSONModel __importDictionary:withKeyMapper:validation:error:] (JSONModel.m:399)
16 MONO                           0x10039af14 -[JSONModel initWithDictionary:error:] (JSONModel.m:190)
17 MONO                           0x1000bd888 -[MONOTeaManager requestLastTeaSuccess:] (MONOTeaManager.m:240)
18 MONO                           0x1000bd5e0 __32-[MONOTeaManager requestLastTea]_block_invoke_2 (MONOTeaManager.m:221)
19 libdispatch.dylib              0x182de94bc _dispatch_call_block_and_release + 24
20 libdispatch.dylib              0x182de947c _dispatch_client_callout + 16
21 libdispatch.dylib              0x182df54c0 _dispatch_queue_drain + 864
22 libdispatch.dylib              0x182decf80 _dispatch_queue_invoke + 464
23 libdispatch.dylib              0x182de947c _dispatch_client_callout + 16
24 libdispatch.dylib              0x182df7914 _dispatch_root_queue_drain + 2140
25 libdispatch.dylib              0x182df70b0 _dispatch_worker_thread3 + 112
26 libsystem_pthread.dylib        0x183001470 _pthread_wqthread + 1092
27 libsystem_pthread.dylib        0x183001020 start_wqthread + 4
```

I received about 70 crash logs until now. All of it have similar problem.

**Comment by HoneyLuka** [comment] 2016-08-29 07:45
By the way, it is similar to #436

**Comment by billinghamj** [comment] 2016-08-29 08:59
Indeed. We are aware, just unfortunately don't have the time to resolve it yet. Closing as a duplicate of #436

**Closed by billinghamj** 2016-08-29 08:59 UTC
